services:
  go-app:
    build: ./go-app
    container_name: go-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - backend
networks:
  backend:
    driver: bridge
