service:
  type: LoadBalancer

ingressRoute:
  dashboard:
    enabled: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    tls: {}
